apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-resize
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: my-resize
    spec:
      containers:
      - name: resize
        image: localhost:5000/my-resize
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5035
